#logging:
#  level:
#    ROOT: DEBUG
#    org.hibernate.SQL: DEBUG
#    com.mycompany.myapp: DEBUG

server:
  port: 8096
  error:
    include-message: always

#cors:
#  allowed-origins: "*"
#  allowed-methods: "*"
#  allowed-headers: "*"
#  exposed-headers: "*"
#
#myapp:
#  security:
#    authentication:
#      jwt:
#        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
#        base64-secret: NmNmZmQyMWIwNTQ0ZjFkZWFjNWMzNzBlMTA5NzE4NWRkZTE0ZGFiYTBmZGM1ZmQ0NTgxMDIzNTBmOTIwYjMyNGM0YzM5YzE2NTJkODRmODQzNDk2ZTk5NDY5ZTBhZTkxMDdlZTQzMWJlODQ2MmU1MzExMGNjNmU3ZTEyOGJjN2U=
#        # Token is valid 24 hours
#        token-validity-in-seconds: 86400
#        token-validity-in-seconds-for-remember-me: 2592000

application:
  name: Sale_management_app


myapp:
  security:
    authentication:
      jwt:
        token-validity-in-seconds: '86400'
        token-validity-in-seconds-for-remember-me: '2592000'
        base64-secret: MWM3MjZhMzk4ZmY2NGJhZmQ5N2IzM2YxNjE4YThkN2ZkYmE2NGIxZTlmMzNiYWRmNjQ0MGJiMjRmNThhNTI2MTMwOTRhNTZhZjI0YmJkMjcyNjM3ZmU5ODJmYzdiMzE0OWQ3NmY3NmI2Y2EyZTQzYzY3M2IyNWU4ZTFkM2Q0YmY=
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  mail:
    host: smtp.gmail.com
    username: pqthanh035
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: lbuekkpeembqhrso
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    password: '123'
    username: root
    url: jdbc:postgresql://localhost:5432/sale_management_db
    type: com.zaxxer.hikari.HikariDataSource

firebase:
  storage:
    bucket: point-of-sale-management.appspot.com
